version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  lint_and_test:
    docker:
      - image: cimg/node:14.20.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: master
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  publish:
    docker:
      - image: cimg/node:14.20.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: |
            set -e

            VERSION=$(node -p "require('./package.json').version")
            PUBLISHED_VERSION=$(npm view @ministryofjustice/module-alias version);

            if [ "$VERSION" != "$PUBLISHED_VERSION" ]
            then
              npm publish
              curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":woohoo:  Successfully published ${CIRCLE_PROJECT_REPONAME} ${VERSION}  :ship_it_parrot:\"}" "$SLACK_WEBHOOK"
            fi
      - slack/status: *slack_status

workflows:
  commit-workflow:
    jobs:
      - lint_and_test
      - publish:
          requires:
            - lint_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
