version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - tomas-stefano
    - brenetic
    - mattempty
    - form-builder-developers
