# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: nvm CI

on:
  push:
    branches: [ github-actions-tests ]
  pull_request:
    branches: [ github-actions-tests ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - run: |
        export NVM_DIR="$HOME/.nvm" 
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm install 5 && nvm use 5
        echo '::set-output name=NVM_DIR::'$NVM_DIR
      id: nvm-setup
    - run: |
        nvm use 5
        node -v
        npm -v
        echo $NVM_DIR
      env: 
        NVM_DIR: ${{ steps.nvm-setup.outputs.NVM_DIR }}
    - run: |
        nvm use 5
        npm install
        npm run testonly
      env: 
        NVM_DIR: ${{ steps.nvm-setup.outputs.NVM_DIR }}

