# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: nvm CI

on:
  push:
    branches: [ github-actions-tests ]
  pull_request:
    branches: [ github-actions-tests ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - run: nvm install 5 && nvm use 5
    - run: node -v
    - run: npm -v
    - run: npm run testonly

